### ISSUE TITLE
对于XModuleResources支持的疑问

### ISSUE THREAD

**Issue by GangJust** [Katana-Official/SPatch-Update#40]
请问，是否不支持xposed的 XModuleResources ？

我尝试后，发现无法通过XModuleResources找到模块中的资源id。

**Comment by OfficialKatana** [comment]
你好，可以找到模块中的资源ID，不过目前需要模块已安装到系统才能找到ID

**Comment by GangJust** [comment]
我是从安装后克隆进去的，但是问题貌似仍然存在，id的确是能拿到，比如模块中的: 0x65aaaaa，但是通过这个id去 XModuleResources 中 getString 或 inflater 后直接崩溃掉了。

**Comment by GangJust** [comment]
另外，还是很感谢回复，我这边已经采用与宿主的资源合并来解决了，不再通过 XModuleResources 去拿资源
